# Preface {.unnumbered}

**Matching and weighting**, a popular special case of which is sometimes known as **propensity score analysis**, are popular methods of adjusting for confounding in observational studies, i.e., studies where patients are not randomly assigned into treatment groups. Despite their popularity in applied research, there are many nuances to the methods that are often missed by researchers, including about the assumptions required, the quantities that can be estimated, and the correct procedures for performing and reporting an analysis. The goal of this guide is to summarize best practices in matching and weighting for medical and social science researchers, highlighting the decisions researchers must make to validly perform and interpret an analysis. This guide is not a substitute for a PhD in biostatistics or even a course in causal inference or propensity score analysis; it should be seen as a starting point that synthesizes the existing literature and provides references for further reading to deepen one's understanding of the methods involved.

### Acknowledgments {.unnumbered}

The guide was written by Noah Greifer ([\@ngreifer](https://github.com/ngreifer)). Special thanks to Steve Worthington, Junjie Liu, Dan Yuan, Josh Cetron, Stefano Iacus, and Gary King for valuable feedback, and for Hossein Estiri for funding an early version of this guide. Thanks to Timothy Chisamore ([\@timchisamore](https://github.com/timchisamore)) for finding errata.